export { default as Paragraph } from './Paragraph/Paragraph'
export { default as Small } from './Small/Small'
export { default as H1 } from './H1/H1'
export { default as H2 } from './H2/H2'
export { default as H3 } from './H3/H3'
