import Head from 'next/head'
import Card from '../../containers/card'
import React, { useState, useEffect } from 'react'
import LayoutPage from '../../containers/LayoutPage'
import products from '../../public/Products/products.json'

export default function Store() {
   const [data, setData] = useState([]);

   useEffect(() => {
      setData(products);
   }, []);

   return (
      <>
         <Head>
            <title>فروشگاه اینترنتی لوازم التحریر</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
         </Head>    
         <LayoutPage>
            <h2>Our Products: </h2>
            {data.length > 0 && (
               <div>
                  {data.map((products) => (
                     <Card key={products.id} data={products} type='normal' />
                  ))}
               </div>
            )}
         </LayoutPage>
         <style jsx>{`
            div{
               display: flex;
               flex-wrap: wrap;
               justify-content: center;
            }

            h2{
               font-size: 25px;
               margin-top: 60px;
               font-weight: 500;
               text-align: center;
               text-shadow: 2px 2px 4px gray;
            }
  
            @media (min-width: 768px) { 
               h2{ font-size: 30px; }
            }
  
            @media (min-width: 992px) { 
               h2{ font-size: 30px; }
            }
  
            @media (min-width: 1200px) { 
               h2{ font-size: 35px; }
            }
        
            @media (min-width: 1600px) { 
               h2{ font-size: 35px; }
            }
         `}</style>
      </>
   );
}
