import React from 'react'
import Head from 'next/head'
import { useSelector } from 'react-redux'
import { Paragraph } from '../../components'
import LayoutPage from '../../containers/LayoutPage'

const success = () => {
   const { logged } = useSelector((state) => state.auth )

   return (
      <>
         <Head>
            <title>خرید موفقیت آمیز</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
         </Head>
         <LayoutPage>
            <div className='main'>
               { logged ?
                  <div className='green'>
                     <Paragraph align='center' type='secondary'>خرید شما با موفقیت انجام شد</Paragraph>
                  </div>
                  :
                  <div className='red'>
                     <Paragraph align='center' type='secondary'>خطایی پیش آمد، شما در حساب خود لاگین نیستید</Paragraph>
                  </div>
               }  
            </div>                
         </LayoutPage>
         <style jsx>{`
            .main{
               height:46vh;
               display:flex;
               align-items:center;
               flex-direction:column;
               justify-content:center;
            }

            .green,.red{
               width:95%;
               padding:3rem;
               border-radius:30px;
            }

            .green{
               background-color:rgba(39, 174, 96, 0.85);
            }

            .red{
               background-color:rgba(231, 76, 60, 0.85);
            }
         `}</style>
      </>
   )
}

export default success