const actionTypes = {
    GET_USER_INFO_STARTED: 'GET_USER_INFO_STARTED',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED',

    REGISTER_STARTED: 'REGISTER_STARTED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    VERIFY_USER_STARTED: 'VERIFY_USER_STARTED',
    VERIFY_USER_SUCCESS: 'VERIFY_USER_SUCCESS',
    VERIFY_USER_FAILED: 'VERIFY_USER_FAILED',

    LOGOUT: 'LOGOUT',

    ADD_TO_CART_STARTED: 'ADD_TO_CART_STARTED',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED',

    GET_CART_PRODUCTS_INFO_STARTED: 'GET_CART_PRODUCTS_INFO_STARTED',
    GET_CART_PRODUCTS_INFO_SUCCESS: 'GET_CART_PRODUCTS_INFO_SUCCESS',
    GET_CART_PRODUCTS_INFO_FAILED: 'GET_CART_PRODUCTS_INFO_FAILED',

    UPDATE_CART_STARTED: 'UPDATE_CART_STARTED',
    UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
    UPDATE_CART_FAILED: 'UPDATE_CART_FAILED',

    REMOVE_FROM_CART_STARTED: 'REMOVE_FROM_CART_STARTED',
    REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
    REMOVE_FROM_CART_FAILED: 'REMOVE_FROM_CART_FAILED',
}

export default actionTypes
