const actionTypes = {
    GET_USER_INFO_STARTED: 'GET_USER_INFO_STARTED',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED',

    REGISTER_STARTED: 'REGISTER_STARTED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    VERIFY_USER_STARTED: 'VERIFY_USER_STARTED',
    VERIFY_USER_SUCCESS: 'VERIFY_USER_SUCCESS',
    VERIFY_USER_FAILED: 'VERIFY_USER_FAILED',

    LOGOUT: 'LOGOUT',
}

export default actionTypes